---
# This role conains tasks to deploy the Oracle Instant Client

- name: installation files check
  shell: ls {{ oracle_client_local_oracle_zip_files_dir }}/instantclient-*.zip
  connection: local
  sudo: false
  register: ls_inst_files
  changed_when: false
  tags: check

- name: installation files missing
  fail: msg="Oracle Instant Client installation files missing"
  when: ls_inst_files.stdout == ""
  tags: check

- name: creating oinstall group
  group: state=present name={{ _oracle_client.group }} gid={{ _oracle_client.group_id }}
  sudo: true

- name: creating oracle user
  user: state=present name={{ _oracle_client.user }} uid={{ _oracle_client.user_id }} group={{ _oracle_client.group  }}
  sudo: true

- name: creating base directory
  sudo: true
  file: path={{ oracle_client_base }} state=directory owner={{ _oracle_client.user }} group={{ _oracle_client.group }}
  tags: install

- name: installing oracle client
  sudo: true
  unarchive: src={{ item }} dest={{ oracle_client_base }}
  with_items: "{{ ls_inst_files.stdout_lines }}"
  tags: install

- name: obtaining installation directory
  shell: ls -d {{ oracle_client_base }}/instantclient_1[012]_*
  register: ls_oracle_home
  changed_when: false
  tags: install

- name: installing cx_Oracle
  pip: name=cx_Oracle state=latest
  when: oracle_client_install_cx_oracle
  environment:
    ORACLE_HOME: "{{ ls_oracle_home.stdout }}"
  tags: install

- name: creating a symbolink link for cx_Oracle
  shell: cd {{ ls_oracle_home.stdout }}; ln -s libclntsh.so.11.1 libclntsh.so
  when: oracle_client_install_cx_oracle
  tags: install
